### PR TITLE
Added Options Menu and Runtime Chart

### PR DESCRIPTION
**Pull request by hoff121324**
This pull request adds a global configuration page and reworks the options area at the top of the page.  It also fixes a couple of minor bugs, and adds an option to plot test runtimes instead of passes/failures.

### CODE REVIEW

**Comment by hoff121324** [comment]
Ok I didn't mean to push the conflict resolution yet, it is not ready.

**Comment by hoff121324** [comment]
I'm pretty sure this check is failing due to the tests committed by a previous merged pull request not being correct.

**Comment by menonvarun** [comment]
I had fixed the tests and pushed to upstream.

**Comment by menonvarun** [comment]
The pull request good. I started working on it sometime back and started with global and job configuration. 
You changes contains only global configuration. Any thoughts on job level configuration if you guys have explored it.

**Comment by hoff121324** [comment]
I agree that a job level configuration makes more sense than only having a global configuration, I can look into adding that.

**Comment by menonvarun** [comment]
Thanks. Earlier pull request contained configuration for the pass, fail, skip colors. Please try to incorporate those also into the job level config along with global if possible.

**Pull request merged**
