### PR TITLE
Add hyperlink to the Test Results Analyzer report

### PR DESCRIPTION
**Pull request by OmarElabd**
1. Added feature to navigate to the jenkins Package, Class or Test from
a link.
2. Refactored ResultData classes to use super constructor.

this resolves JENKINS-24266.

### CODE REVIEW

**Comment by gs-vmenon** [comment]
Please latest pull changes from master and work on it. 
Also please format and add only the newly added code and not the whole file.

You have reverted the changes for supporting testng in the plugin. Please take a look at the pull request and work on it.

**Comment by menonvarun** [comment]
Please pull latest changes from master and work on it. 
Also please format and add only the newly added code and not the whole file.

You have reverted the changes for supporting testng in the plugin. Please take a look at the pull request and work on it.

**Comment by OmarElabd** [comment]
Should be good now

**Comment by menonvarun** [comment]
I was going through  the plugin and found that the result url shows junit link. It will be good if it can link to testng results if available

**Comment by OmarElabd** [comment]
I'm not very familiar with TestNG, does it have a similar url pattern to the junit test?

**Comment by menonvarun** [comment]
Yes. But there is testresults added to the url.. ok let me check myself

**Pull request merged**
