### PR TITLE
Added several new features, adjusted UI, added tests

### PR DESCRIPTION
**Pull request by hoff121324**
Added new features:
 * Entry in global configurations page
 * Cleaned up options menu
 * Added test filters through both text searches and filtering statuses
 * Added support for graphing test runtimes
 * Indicator for newly failing tests
 * Allowed user to configure table colors and text
 * Adjusted charts to avoid some decimals and negatives
 * Commit ownership tracking
 * Option to hide failed builds
 * Test Results Analyzer page now automatically loads (User does not need to click Get Build Report/Generate Charts)
 * Added links to individual test reports
 * Added unit tests and integration tests with selenium/chrome
 * Added error messages when no builds are available or the user needs to click on "modules"

Additionally, there are quite a few formatting adjustments and minor refactorings

### CODE REVIEW

**Comment by hoff121324** [comment]
If you would like us to break this up into a couple of separate pull requests for various features, let us know.

**Comment by menonvarun** [comment]
Please raise separate pull request for each feature.
Please use htmlunit for selenium tests as it removes dependency of configuring external chrome driver.

Please send a out a separate mail to me explaining about certain features implemented or raise a Jira feature request for the same.

**Comment by menonvarun** [comment]
Also please try to format only the code that is newly added rather than the whole class.

**Comment by hoff121324** [comment]
I'm going to close this pull request and open a different one from a different branch.

**Pull request closed without merging**
