### PR TITLE
Increase Jenkins version to 2.440.3

### PR DESCRIPTION
**Pull request by mPokornyETM**
Increase Jenkins version 2.440.1 to allow next feature development

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by MarkEWaite** [comment]
I was a little surprised by the choice of 2.440.1 as the baseline.  The recommendation from the [documentation](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions) is currently either 2.414.3 or 2.426.3

I'm fine with this change but was surprised.  Was there a specific reason you chose this version as the base?

**Comment by mPokornyETM** [comment]
> I was a little surprised by the choice of 2.440.1 as the baseline. The recommendation from the [documentation](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions) is currently either 2.414.3 or 2.426.3
> 
> I'm fine with this change but was surprised. Was there a specific reason you chose this version as the base?

There is no specific reason. The same docu https://github.com/jenkinsci/lockable-resources-plugin/pull/642 says, that it might ber used. And we have currently the same version on our productive system. And I dont want to change the version in plugin so rapidly. Therefore the highest as possible.

**Comment by MarkEWaite** [comment]
@mPokornyETM I've incremented the minimum Jenkins version to 2.440.3 and switched the pom file to use the `jenkins.baseline` technique that is now used in the Jenkins plugin archetype.  That aligns the plugin BOM version number with the minimum Jenkins version.

**Comment by mPokornyETM** [comment]
> Jenkins plugin archetype

Migh you passte here some link with the example please?. Thx

**Comment by MarkEWaite** [comment]
> Might you paste here some link with the example please?. Thx

The Jenkins plugin archetype has been updated to include a baseline version string (`jenkins.baseline`) that is used to provide both the Jenkins minimum version (`jenkins.version`) and the artifactId of the plugin BOM.  Refer to the pull request:

* https://github.com/jenkinsci/archetypes/pull/737

A request has also been made that recommends an OpenRewrite recipe be created to perform the transformation so that it can be done more easily.  That request is:

* https://github.com/jenkinsci/archetypes/issues/738

This pull request is manually performing the transformation that eventually it is hoped will be done with an [OpenRewrite recipe](https://app.moderne.io/marketplace/org.openrewrite.jenkins.core).  There are already many useful OpenRewrite recipes for Jenkins in addition to the more general OpenRewrite recipes for Java development that can be used for Jenkins plugins.

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
