### PR TITLE
Support TestNG by using reflection as dependency might not be wanted

### PR DESCRIPTION
**Pull request by benzman81**

### CODE REVIEW

**Comment by roydekleijn** [comment]
does this solve the following ?

I see only the latest build. I use TestNG as test runner.

**Comment by benzman81** [comment]
I dont have this issue, so I guess it does.

**Comment by roydekleijn** [comment]
cool, can you send me a valid .HPI file? as I was not able to create it by maven.

**Comment by menonvarun** [comment]
I am testing some changes and I dont see the issue you mentioned.
Can you confirm that you are using junit publish results option pointing to
junit xml file generated by testng.

**Comment by benzman81** [comment]
We use "Publish TestNG Results" as JUnit seems to have errors with TestNG that makes the tests seem stable although they are not.

**Comment by roydekleijn** [comment]
I'm using both at the moment (is that the issue ?)

**Comment by roydekleijn** [comment]
Any update on this?

**Pull request merged**
