### PR TITLE
Simple change, reduced complexity of the for loop.

### PR DESCRIPTION
**Pull request by OmarElabd**

### CODE REVIEW

**Comment by menonvarun** [comment]
The issue with this change will be when user wants to see only few last builds. The said code change will show build from the starting rather than last.

**Comment by OmarElabd** [comment]
Hmm maybe there is something i'm missing? They look equivalent to me.

Created a comparison:
http://goo.gl/LjKUi3

**Comment by hoff121324** [comment]
Notice that he also reversed the order of iteration to go from first to last.  Because of this, it is not necessary to reverse the list after the loop.

**Comment by menonvarun** [comment]
Agree with you guys.

**Pull request merged**
